-- Baseline schema for viajes-eventos-api. Applied automatically at startup by
-- org.viajeseventos.db.MigrationRunner — do not run this by hand.
--
-- Access control follows the condominios pattern: every user has exactly one profile, and a
-- profile grants a set of modules (profile_modules.module_key mirrors org.viajeseventos.model.AppModule).
-- The frontend shows a module's pages and the API serves its routes only when the caller's profile
-- grants it, so enabling/disabling features per profile is pure data — edited from the profile
-- maintainer (PROFILES module), no deploy needed.

CREATE TABLE IF NOT EXISTS profiles (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Stable identifier for the system profiles the code relies on (ADMIN, CLIENT); NULL for
    -- profiles created from the maintainer. Lets their display name change without breaking code.
    code        VARCHAR(50),
    name        VARCHAR(100) NOT NULL,
    description TEXT,
    created_at  TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMP,
    CONSTRAINT uk_profiles_code UNIQUE (code)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_profiles_name_ci ON profiles (LOWER(name));

CREATE TABLE IF NOT EXISTS profile_modules (
    profile_id BIGINT      NOT NULL,
    module_key VARCHAR(50) NOT NULL,
    PRIMARY KEY (profile_id, module_key),
    CONSTRAINT fk_profile_modules_profile FOREIGN KEY (profile_id) REFERENCES profiles (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS users (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username       VARCHAR(255) NOT NULL,
    email          VARCHAR(255) NOT NULL,
    password       VARCHAR(255) NOT NULL,
    first_name     VARCHAR(255),
    last_name      VARCHAR(255),
    phone          VARCHAR(255),
    -- NO ACTION on delete: a profile still assigned to users can't be removed out from under them.
    profile_id     BIGINT       NOT NULL,
    enabled        BOOLEAN      NOT NULL DEFAULT TRUE,
    email_verified BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at     TIMESTAMP,
    updated_at     TIMESTAMP,
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT fk_users_profile FOREIGN KEY (profile_id) REFERENCES profiles (id)
);

CREATE INDEX IF NOT EXISTS idx_users_profile_id ON users (profile_id);

INSERT INTO profiles (code, name, description) VALUES
    ('ADMIN',  'Administrador', 'Administrador del sistema — acceso completo'),
    ('CLIENT', 'Cliente',       'Cliente — ve eventos y registra viajes');

-- ADMIN's module list is also re-synced to every AppModule at startup (AdminBootstrap), so modules
-- added in later versions reach it without a migration.
INSERT INTO profile_modules (profile_id, module_key)
SELECT id, m FROM profiles, (VALUES ('EVENTS'), ('USERS'), ('PROFILES')) AS modules(m)
WHERE code = 'ADMIN';

INSERT INTO profile_modules (profile_id, module_key)
SELECT id, 'EVENTS' FROM profiles WHERE code = 'CLIENT';

-- The administrator account is created at startup by org.viajeseventos.AdminBootstrap, never
-- seeded here with a fixed password.
