-- Events move from the frontend's static list into the database so bookings can reference them,
-- and bus reservations ("bookings") with their passengers.

CREATE TABLE IF NOT EXISTS events (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug       VARCHAR(120) NOT NULL,
    name       VARCHAR(255) NOT NULL,
    venue      VARCHAR(255) NOT NULL,
    commune    VARCHAR(120) NOT NULL,
    category   VARCHAR(120),
    image_url  VARCHAR(500),
    start_date DATE         NOT NULL,
    end_date   DATE,
    source_url VARCHAR(500),
    active     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP    NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_events_slug UNIQUE (slug),
    CONSTRAINT ck_events_dates CHECK (end_date IS NULL OR end_date >= start_date)
);

-- One booking = one checkout from the "Viajar" modal: a group of passengers for one event,
-- made by one account. Cancelling keeps the row (status) for the record.
CREATE TABLE IF NOT EXISTS bookings (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id     BIGINT      NOT NULL,
    user_id      BIGINT      NOT NULL,
    status       VARCHAR(20) NOT NULL DEFAULT 'CONFIRMED',
    created_at   TIMESTAMP   NOT NULL DEFAULT NOW(),
    cancelled_at TIMESTAMP,
    CONSTRAINT fk_bookings_event FOREIGN KEY (event_id) REFERENCES events (id),
    CONSTRAINT fk_bookings_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT ck_bookings_status CHECK (status IN ('CONFIRMED', 'CANCELLED'))
);

CREATE INDEX IF NOT EXISTS idx_bookings_event_id ON bookings (event_id);
CREATE INDEX IF NOT EXISTS idx_bookings_user_id ON bookings (user_id);

CREATE TABLE IF NOT EXISTS booking_passengers (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id      BIGINT       NOT NULL,
    position        INT          NOT NULL,
    full_name       VARCHAR(200) NOT NULL,
    phone           VARCHAR(30)  NOT NULL,
    departure_place VARCHAR(200) NOT NULL,
    departure_time  TIME         NOT NULL,
    return_place    VARCHAR(200) NOT NULL,
    CONSTRAINT fk_booking_passengers_booking FOREIGN KEY (booking_id) REFERENCES bookings (id) ON DELETE CASCADE,
    CONSTRAINT uk_booking_passengers_position UNIQUE (booking_id, position)
);

-- Taken from puntoticket.com's home page (September 2026) — same 10 events the UI shipped with.
INSERT INTO events (slug, name, venue, commune, category, image_url, start_date, end_date, source_url) VALUES
    ('mana', 'Maná - Vivir sin aire Tour', 'Estadio Monumental', 'Macul', 'Pop-Rock',
     'https://static.ptocdn.net/images/eventos/biz383_calugalistado.jpg', '2026-12-05', NULL, 'https://www.puntoticket.com/mana'),
    ('karol-g', 'Karol G - Viajando por el Mundo TropiTour', 'Estadio Nacional', 'Ñuñoa', 'Urbano',
     'https://static.ptocdn.net/images/eventos/biz378_calugalistado.jpg', '2027-01-28', '2027-01-31', 'https://www.puntoticket.com/karol-g'),
    ('creamfields-2026', 'Creamfields Chile 2026 - 21 Años', 'Club Hípico', 'Santiago Centro', 'Electrónica',
     'https://static.ptocdn.net/images/eventos/sm0194_calugalistado.jpg', '2026-11-14', '2026-11-15', 'https://www.puntoticket.com/creamfields-2026'),
    ('cadillacs-fishbone-2026', 'Los Fabulosos Cadillacs + Fishbone + Chico Trujillo', 'Santander Arena', 'Santiago Centro', 'Rock',
     'https://static.ptocdn.net/images/eventos/cco111_calugalistado.jpg', '2026-10-29', NULL, 'https://www.puntoticket.com/cadillacs-fishbone-2026'),
    ('def-leppard', 'Def Leppard - Live 2026 - with Special Guest Extreme', 'Santander Arena', 'Santiago Centro', 'Rock',
     'https://static.ptocdn.net/images/eventos/rec113_calugalistado.jpg', '2026-11-08', NULL, 'https://www.puntoticket.com/def-leppard'),
    ('deep-purple', 'Deep Purple', 'Santander Arena', 'Santiago Centro', 'Hard Rock',
     'https://static.ptocdn.net/images/eventos/rec112_calugalistado.jpg', '2026-12-08', NULL, 'https://www.puntoticket.com/deep-purple'),
    ('oktoberfest-2026', 'Oktoberfest 2026', 'Centro de Eventos Múnich', 'Peñaflor', 'Festival Bávaro',
     'https://static.ptocdn.net/images/eventos/fex013v2_calugalistado.jpg', '2026-10-09', '2026-10-11', 'https://www.puntoticket.com/oktoberfest-2026'),
    ('cirque-du-soleil-alegria', 'Cirque du Soleil - Alegria', 'Espacio Riesco', 'Huechuraba', 'Familia',
     'https://static.ptocdn.net/images/eventos/ipr002v4_calugalistado.jpg', '2027-01-06', '2027-01-31', 'https://www.puntoticket.com/cirque-du-soleil-alegria'),
    ('faunaprimavera', 'Festival Fauna Primavera 2026', 'Parque Ciudad Empresarial', 'Huechuraba', 'Festival',
     'https://static.ptocdn.net/images/eventos/fna377v2_calugalistado.jpg', '2026-11-26', '2026-11-28', 'https://www.puntoticket.com/faunaprimavera'),
    ('santiago-rocks-2026', 'Santiago Rocks - 2026', 'Arena Hipódromo', 'Independencia', 'Festival',
     'https://static.ptocdn.net/images/eventos/jts127_calugalistado.jpg', '2026-12-13', NULL, 'https://www.puntoticket.com/santiago-rocks-2026');
