-- Multi-company: each transport company (tenant) has its own administrators, clients and events.
-- Companies sign themselves up; clients register through their company's link (/empresa/<slug>).
-- Everything already in the database becomes the first company's.

CREATE TABLE IF NOT EXISTS companies (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(150) NOT NULL,
    slug          VARCHAR(60)  NOT NULL,
    -- Reply-To of the emails sent on the company's behalf (the From address is the platform's SMTP).
    contact_email VARCHAR(255),
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMP,
    CONSTRAINT uk_companies_slug UNIQUE (slug)
);

INSERT INTO companies (name, slug, contact_email)
SELECT 'Viajes a Eventos', 'viajes-eventos',
       (SELECT u.email FROM users u JOIN profiles p ON p.id = u.profile_id WHERE p.code = 'ADMIN' ORDER BY u.id LIMIT 1);

-- Users: every account belongs to one company. platform_admin marks the platform owner(s), who on
-- top of their profile get the platform modules (PROFILES, SETTINGS, COMPANIES) — see AppModule.
ALTER TABLE users ADD COLUMN company_id BIGINT;
ALTER TABLE users ADD COLUMN platform_admin BOOLEAN NOT NULL DEFAULT FALSE;
UPDATE users SET company_id = (SELECT id FROM companies WHERE slug = 'viajes-eventos');
UPDATE users SET platform_admin = TRUE WHERE profile_id = (SELECT id FROM profiles WHERE code = 'ADMIN');
ALTER TABLE users ALTER COLUMN company_id SET NOT NULL;
ALTER TABLE users ADD CONSTRAINT fk_users_company FOREIGN KEY (company_id) REFERENCES companies (id);
CREATE INDEX IF NOT EXISTS idx_users_company_id ON users (company_id);

-- Events: each company has its own catalog; slugs only need to be unique within it.
ALTER TABLE events ADD COLUMN company_id BIGINT;
UPDATE events SET company_id = (SELECT id FROM companies WHERE slug = 'viajes-eventos');
ALTER TABLE events ALTER COLUMN company_id SET NOT NULL;
ALTER TABLE events ADD CONSTRAINT fk_events_company FOREIGN KEY (company_id) REFERENCES companies (id);
ALTER TABLE events DROP CONSTRAINT uk_events_slug;
ALTER TABLE events ADD CONSTRAINT uk_events_company_slug UNIQUE (company_id, slug);

-- Platform modules are no longer granted through profiles (profiles are shared by every company).
DELETE FROM profile_modules WHERE module_key IN ('PROFILES', 'SETTINGS');
